  clickhouse-server:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: 1g
    ports:
      - "8123:8123"
    volumes:
      - /docker/clickhouse_data:/Users/vladpodsadnyj/compose

  postgres:
    image: postgres
    restart: unless-stopped
    cpus: "1.0"
    ports:
      - "8888:8888"
    volumes:
      - /docker/postgres:/Users/vladpodsadnyj/compose
